# Generated by Django 4.0.4 on 2022-05-07 23:32

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_status', models.BooleanField(default=False)),
                ('confirmation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'db_table': 'order_documents',
            },
        ),
        migrations.CreateModel(
            name='TMVOrderDocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_number', models.FloatField()),
                ('actual_number', models.FloatField(default=0.0)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_document_items', to='orders.orderdocumentmodel')),
            ],
            options={
                'db_table': 'tmvs_orders',
            },
        ),
    ]
