# Generated by Django 4.0.4 on 2022-05-07 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tmvs', '0001_initial'),
        ('counterparties', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmvorderdocumentmodel',
            name='tmv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_orders', to='tmvs.tmvmodel'),
        ),
        migrations.AddField(
            model_name='orderdocumentmodel',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to='counterparties.counterpartymodel'),
        ),
        migrations.AddField(
            model_name='orderdocumentmodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provided_orders', to='counterparties.counterpartymodel'),
        ),
    ]
