# Generated by Django 4.0.5 on 2022-06-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderdocumentmodel_confirmation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmvorderdocumentmodel',
            name='comment',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
