# Generated by Django 4.0.4 on 2022-05-12 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movementdocumentmodel',
            name='receiver',
        ),
        migrations.AddField(
            model_name='movementdocumentmodel',
            name='from_warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sent_movements', to='warehouses.warehousemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movementdocumentmodel',
            name='to_warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='received_movements', to='warehouses.warehousemodel'),
            preserve_default=False,
        ),
    ]
