# Generated by Django 4.0.4 on 2022-05-07 23:32

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurements', '0001_initial'),
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'tmvs',
            },
        ),
        migrations.CreateModel(
            name='TMVTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'tmv_types',
            },
        ),
        migrations.CreateModel(
            name='TMVUnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
            ],
            options={
                'db_table': 'units',
            },
        ),
        migrations.CreateModel(
            name='TMVWarehouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField(default=0.0)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('date', models.DateField()),
                ('confirmation_status', models.BooleanField(default=False)),
                ('movement_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_document_items', to='movements.movementdocumentmodel')),
                ('procurement_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_document_items', to='procurements.procurementdocumentmodel')),
                ('tmv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tmvs.tmvmodel')),
            ],
            options={
                'db_table': 'tmvs_warehouses',
            },
        ),
    ]
