# Generated by Django 4.0.4 on 2022-05-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmvs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmvwarehousemodel',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
