# Generated by Django 4.0.4 on 2022-05-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmvs', '0006_alter_tmvwarehousemodel_movement_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmvwarehousemodel',
            name='comment',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
