# Generated by Django 4.0.5 on 2022-06-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmvs', '0007_tmvwarehousemodel_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmvwarehousemodel',
            name='date',
            field=models.DateField(),
        ),
    ]
