# Generated by Django 4.0.4 on 2022-05-07 23:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'counterparty_types',
            },
        ),
        migrations.CreateModel(
            name='CounterpartyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('contact_data', models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13)])),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counterparties', to='counterparties.counterpartytypemodel')),
            ],
            options={
                'db_table': 'counterparties',
            },
        ),
    ]
